apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: datadoc
  title: Datadoc
  description: |
    Document datasets in SSB
  tags:
    - dapla
    - metadata
    - python
    - dash
  annotations:
    github.com/project-slug: statisticsnorway/datadoc
spec:
  type: service
  owner: dapla-metadata-developers
  lifecycle: experimental
  dependsOn: dapla-beta
  system: dapla-metadata
