apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: datadoc-editor
  title: Datadoc Editor
  description: |
    Create and edit documentation for datasets at Statistics Norway
  tags:
    - dapla
    - metadata
    - python
    - dash
  annotations:
    github.com/project-slug: statisticsnorway/datadoc-editor
spec:
  type: service
  owner: dapla-metadata-developers
  lifecycle: production
  dependsOn:
    - system:dapla-lab
    - component:dapla-toolbelt-metadata
    - component:ssb-dash-components
  consumesApis:
    - api:klass-api
  system: metadata
