name: Integration test

on:
  pull_request:
    paths:
      - "src/datadoc/**"
      - "poetry.lock"
      - ".nais/staging-pr.yaml"
      - ".github/workflows/integration-test.yml"

jobs:
  docker-build:
    name: Docker build
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          # Push to registry, Salsa and caching are enabled by default
          team: dapla-metadata
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ secrets.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: staging
          RESOURCE: .nais/staging-pr.yaml
          VAR: image=${{ needs.docker-build.outputs.image-tag }},pr-number=${{github.event.number}}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
